// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhtcadrxmcubwhgpohun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRodGNhZHJ4bWN1YndoZ3BvaHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDI2MzgsImV4cCI6MjA2Nzg3ODYzOH0.yamtDZ3tmJWImG9URQHqMp8PbsXr_N78N62jUl3H_lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});